#!/usr/bin/env python

import sys

from multi_signals_annotator.bag import Bag
from rqt_gui.main import Main

plugin = 'multi_signals_annotator.bag.Bag'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Bag.add_arguments))
